services:
  wgd:
    image: ghcr.io/jinndi/wgdashboard-sing-box:latest
    container_name: wgd
    restart: unless-stopped
    environment:
      TZ: ""             # Default: Europe/Amsterdam
      WGD_PATH: ""       # Default: <empty> (Path to the WEB panel without / in the address bar)
      WGD_HOST: ""       # Domain or IP. Autodetect IP by default (for WG clients)
      WGD_PORT: ""       # Default: 10086 (WEB UI, for Caddy revers proxy)
      DNS_CLIENTS: ""    # Default: 1.1.1.1 (for WG clients)
      DNS_DIRECT: ""     # Default: 77.88.8.8 (DoH, for sing-box)
      DNS_PROXY: ""      # Default: 1.1.1.1 (DoH, for sing-box)
      CIDR_PROXY: ""     # Default: 10.10.10.0/24 (More through comma)
      PROXY_LINK: ""     # Support: VLESS-TCP-REALITY xtls-rprx-vision
      GEOSITE_BYPASS: "" # Example: category-ru,geolocation-cn,...
      GEOIP_BYPASS: ""   # Example: ru,by,...
      GEO_NO_DOMAINS: "" # Example: vk.com,habr.com,4pda,...
    ports:
      - 51820-51830:51820-51830/udp
    volumes:
      - wgd_data:/data
      - wgd_wgconf:/etc/wireguard
      - wgd_awgconf:/etc/amnezia/amneziawg
      - /lib/modules:/lib/modules:ro
    networks:
      - wgd_net
    privileged: true

  wgd-caddy:
    image: docker.io/library/caddy:2.10-alpine
    restart: unless-stopped
    container_name: wgd-caddy
    entrypoint: /bin/sh -c 'echo -e "
        input-your-domain.com
        tls input-your@mail.com
        reverse_proxy wgd:10086
      ">/Caddyfile && caddy run -c /Caddyfile -a caddyfile'
    ports:
      - 443:443/tcp
      - 443:443/udp
    volumes:
      - wgd_caddydata:/data
      - wgd_caddyconf:/config
    networks:
      - wgd_net
    cap_add:
      - NET_ADMIN

volumes:
  wgd_data:
    name: wgd_data
    driver: local
  wgd_wgconf:
    name: wgd_wgconf
    driver: local
  wgd_awgconf:
    name: wgd_awgconf
    driver: local
  wgd_caddydata:
    name: wgd_caddydata
    driver: local
  wgd_caddyconf:
    name: wgd_caddyconf
    driver: local

networks:
  wgd_net:
    name: wgd_net
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
        - subnet: fd12:3456:789a:1::/64
