name: Docker publish Caddy

on:
  workflow_dispatch: ~

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  IMAGE_VERSION: 2.10
  IMAGE_NAME: caddy

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Caddy
        id: meta_caddy
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.IMAGE_VERSION }}

      - name: Build and push Caddy image
        uses: docker/build-push-action@v5
        with:
          context: ./caddy
          push: true
          tags: ${{ steps.meta_caddy.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta_caddy.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max